### ISSUE TITLE
Building package fails

### ISSUE THREAD

**Issue by SamoPP** [taylorizing/options.data#1]
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘options.data’ ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error : Problem with `mutate()` input `day.week`.
✖ no applicable method for 'weekdays' applied to an object of class "c('double', 'numeric')"
ℹ Input `day.week` is `weekdays(open.first.day.week$date, abbreviate = FALSE)`.
Error: unable to load R code in package ‘options.data’
Execution halted
ERROR: lazy loading failed for package ‘options.data’
* removing ‘/usr/local/lib/R/site-library/options.data’

**Comment by themechanicalbear** [comment]
the build issue was due to some old date logic that was updated with lubridate::days.  it should work now. it is old so not sure how much use it will be, but have a go with it and let me know.

**Comment by SamoPP** [comment]
Package now builds without any problems. Thanks.

I have found another issue in the https://github.com/taylorizing/options.shiny though. I thought it was linked to options.data but it looks like a separate thing. Will open an issue there.
